### ISSUE TITLE
Error when starting project

### ISSUE THREAD

**Issue by TJJP** [kylejramstad/garage-pi-v2#19]
I got this project downloaded and ran the install with npm, but I keep getting this error and I can't figure it out. What could I be doing wrong?

```
garage@Dee:~/garage-pi-v2 $ sudo npm start server.js

> garage_pi@2.1.6 start
> node server.js "server.js"

/home/garage/garage-pi-v2/node_modules/rpio/lib/rpio.js:385
                        throw new Error(errstr);
                        ^

Error: Pin NaN is not valid when using physical mapping
    at pin_to_gpio (/home/garage/garage-pi-v2/node_modules/rpio/lib/rpio.js:385:10)
    at rpio.open (/home/garage/garage-pi-v2/node_modules/rpio/lib/rpio.js:533:16)
    at startPins (/home/garage/garage-pi-v2/controllers/pinsController.js:70:7)
    at Object.<anonymous> (/home/garage/garage-pi-v2/controllers/pinsController.js:60:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code 1
npm ERR! path /home/garage/garage-pi-v2
npm ERR! command failed
npm ERR! command sh -c node server.js "server.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-19T06_55_23_905Z-debug.log
```

**Comment by kylejramstad** [comment]
Not sure what you mean by "ran the install with npm".
Installing this software has been automated. Please read the readme instructions.
You should be running garage-pi inside a docker container. This is done for easy compatibility when new raspberry pi versions come out and for security of your home network since it is going to be exposed to the open internet.

**Comment by TJJP** [comment]
I was building the project inside of a docker container and it was just dying imminently. So I tried to run it outside with NPM and node and it was just erroring out so maybe this information will help debug it.
